### ISSUE TITLE
how to use & sign in password

### ISSUE THREAD

**Issue by Hamed1984** [cafebazaar/bundle-signer#14]
سلام

اگر در پسورد از علامت & استفاده کنم برنامه با خطا مواجه میشه و فکر میکنه هرچی که بعد از علامت & هست باید یک دستور دیگه باشه
انتهای پسورد من با &sq تمام می شود

راهکار چیست؟

error: Failed to load signer "signer #1"
java.io.IOException: Keystore was tampered with, or password was incorrect
	at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:792)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:243)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at ir.cafebazaar.bundlesigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:364)
	at ir.cafebazaar.bundlesigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:250)
	at ir.cafebazaar.bundlesigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:183)
	at ir.cafebazaar.bundlesigner.BundleSignerTool.getSignerConfig(BundleSignerTool.java:436)
	at ir.cafebazaar.bundlesigner.BundleSignerTool.getContentDigest(BundleSignerTool.java:345)
	at ir.cafebazaar.bundlesigner.BundleSignerTool.main(BundleSignerTool.java:125)
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:790)
	... 8 more
'sq' is not recognized as an internal or external command,
operable program or batch file.

**Comment by mahboobehad** [comment]
سلام 
می‌تونید پسورد رو به شکل زیر وارد کنید 
--ks-pass pass:'&sq'

**Comment by Hamed1984** [comment]
سلام
داخل سینگل کوتیشن ' هم گذاشتم باز هم همون خطا رو میده
