### ISSUE TITLE
درخواست اضافه کردن متن خطا

### ISSUE THREAD

**Issue by sajaddp** [cafebazaar/bundle-signer#22]
سلام
این خطا به چه دلیلی است؟
```
Failed to load signer "signer #1"
java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.
	at sun.security.util.DerInputStream.getLength(DerInputStream.java:605)
	at sun.security.util.DerValue.init(DerValue.java:391)
	at sun.security.util.DerValue.<init>(DerValue.java:332)
	at sun.security.util.DerValue.<init>(DerValue.java:345)
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1941)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at ir.cafebazaar.bundlesigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:364)
	at ir.cafebazaar.bundlesigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:250)
	at ir.cafebazaar.bundlesigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:183)
	at ir.cafebazaar.bundlesigner.BundleSignerTool.getSignerConfig(BundleSignerTool.java:438)
	at ir.cafebazaar.bundlesigner.BundleSignerTool.getContentDigest(BundleSignerTool.java:347)
	at ir.cafebazaar.bundlesigner.BundleSignerTool.main(BundleSignerTool.java:125)
```

دستور اجرا شده:
```
java -jar bundlesigner-0.1.7.jar genbin  -v --bundle app-release.aab  --bin .  --v2-signing-enabled true --v3-signing-enabled false --ks mykeystore.keystore --ks-type PKCS12
```

**Comment by sajaddp** [comment]
سلام
خروجی به این صورت هست:
```
Keystore type: jks
Keystore provider: SUN
```
ممنون می شوم بفرمایید باید از چه روشی استفاده کنیم؟

**Comment by srmarjani** [comment]
سلام وقتتون بخیر.
در نسخه جدید خطاهای سمت کاربر بهبود پیدا کرده.
لطفا با نسخه جدید تست کنید

**Comment by sajaddp** [comment]
سلام
امروز با نسخه `0.1.9` تست کردم متاسفانه اطلاعات برگشتی به کار نمیاد.

ممنون از توجه تون فعلا از همان روش قدیم برای کافه بازار استفاده می کنیم تا بعدا که شمافرصت کنید آپدیت کاملی ارائه دهید.

**Comment by blackmoonstudio** [comment]
سلام لطفا ابزارتون رو بهبود بدید خیلی ضعیف در این مورد عمل کردید

**Comment by mahboobehad** [comment]
سلام وقتتون بخیر
لطفا مشکلی که داشتید رو در یک ایشوی جدید برای ما بفرستید تا بررسی کنیم.
