### ISSUE TITLE
java.io.IOException: error=2, No such file or directory

### ISSUE THREAD

**Issue by amirkhaki** [cafebazaar/bundle-signer#33]
سلام
دستوری که اجرا میکنم 
`java -jar bundlesigner-0.1.11.jar genbin  -v --bundle app.aab --bin .  --v2-signing-enabled true --v3-signing-enabled false --ks signing.keystore `
بعد از وارد کردن پسوردها، ارور زیر رو میده
```
Error when executing command: [/tmp/AutoValue_BuildApksCommand8099214261507423403/output/linux/aapt2, convert, --output-format, binary, -o, /tmp/14895544467287370666/binary6.apk, /tmp/14895544467287370666/proto2.apk]
[com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57), com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:64), com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:33), com.android.tools.build.bundletool.androidtools.Aapt2Command$1.convertApkProtoToBinary(Aapt2Command.java:53), com.android.tools.build.bundletool.io.Aapt2ResourceConverter$ResourceConverter.convertAndOptimizeProtoApk(Aapt2ResourceConverter.java:156), com.android.tools.build.bundletool.io.Aapt2ResourceConverter$ResourceConverter.convertResourcesToBinary(Aapt2ResourceConverter.java:116), com.android.tools.build.bundletool.io.Aapt2ResourceConverter.lambda$null$2(Aapt2ResourceConverter.java:96), com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125), com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69), com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]
Aug 07, 2022 12:20:46 PM com.google.common.util.concurrent.AggregateFuture log
SEVERE: Got more than one input Future failure. Logging failures after the first
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Error when executing command: [/tmp/AutoValue_BuildApksCommand8099214261507423403/output/linux/aapt2, convert, --output-format, binary, -o, /tmp/14895544467287370666/binary5.apk, /tmp/14895544467287370666/proto4.apk]
        at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
        at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:64)
        at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:33)
        at com.android.tools.build.bundletool.androidtools.Aapt2Command$1.convertApkProtoToBinary(Aapt2Command.java:53)
        at com.android.tools.build.bundletool.io.Aapt2ResourceConverter$ResourceConverter.convertAndOptimizeProtoApk(Aapt2ResourceConverter.java:156)
        at com.android.tools.build.bundletool.io.Aapt2ResourceConverter$ResourceConverter.convertResourcesToBinary(Aapt2ResourceConverter.java:116)
        at com.android.tools.build.bundletool.io.Aapt2ResourceConverter.lambda$null$2(Aapt2ResourceConverter.java:96)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Cannot run program "/tmp/AutoValue_BuildApksCommand8099214261507423403/output/linux/aapt2": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:44)
        ... 11 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 13 more
```
ورژن جاوا
`openjdk version "11.0.16" 2022-07-19`

**Comment by mahboobehad** [comment]
سلام 
می‌شه بسته‌های زیر رو نصب کنید و دوباره دستور تولید فایل bin رو بزنید؟

sudo apt-get install lib32stdc++6
sudo apt-get install lib32z1
