### ISSUE TITLE
java.io.IOException: parseAlgParameters failed: ObjectIdentifier() -- data isn't an object ID (tag = 48)

### ISSUE THREAD

**Issue by Behzad0017** [cafebazaar/bundle-signer#37]
سلام وقت بخیر 
بعد از اجرای دستورات زیر 
java -jar bundlesigner-0.1.12.jar genbin --bundle luca.aab --bin D:\ --v2-signing-enabled true --v3-signing-enabled false --ks key.jks -v

و وارد کردن پسورد
Keystore password for signer #1:

 خطای زیر رو دریافت میکنم
java.io.IOException: parseAlgParameters failed: ObjectIdentifier() -- data isn't an object ID (tag = 48)
        at java.base/sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(Unknown Source)
        at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(Unknown Source)
        at java.base/sun.security.util.KeyStoreDelegator.engineLoad(Unknown Source)
        at java.base/java.security.KeyStore.load(Unknown Source)
        at ir.cafebazaar.bundlesigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:364)
        at ir.cafebazaar.bundlesigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:250)
        at ir.cafebazaar.bundlesigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:183)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.getSignerConfig(BundleSignerTool.java:443)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.getContentDigest(BundleSignerTool.java:352)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.main(BundleSignerTool.java:126)
Caused by: java.io.IOException: ObjectIdentifier() -- data isn't an object ID (tag = 48)
        at java.base/sun.security.util.ObjectIdentifier.<init>(Unknown Source)
        at java.base/sun.security.util.DerInputStream.getOID(Unknown Source)
        at java.base/com.sun.crypto.provider.PBES2Parameters.engineInit(Unknown Source)
        at java.base/java.security.AlgorithmParameters.init(Unknown Source)
        ... 10 more

ورژن جاوا
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

حدود یک ماه پیش با همین دستورات برای یه برنامه دیگه خروجی گرفتم ولی برای این برنامه این خطا رو میده

ممنون میشم راهنمایی کنید

**Comment by Behzad0017** [comment]
با تشکر از پاسخوگویی شما

**Comment by feryt20** [comment]
مشکلتون حل شد؟
چیکارش کردید؟
منم همین مشکل رو دارم
