### ISSUE TITLE
خطای java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by amoozesh3** [cafebazaar/bundle-signer#38]
سلام. هنگام خروجی گرفتن از فایل باندل ساینر با خطای زیر مواجه می شوم. اسکرین شات ضمیمه شد:

```
Keystore password for signer #1:

Nov 16, 2022 8:13:38 PM com.google.common.util.concurrent.AggregateFuture log

SEVERE: Input Future failed with Error

java.lang.OutOfMemoryError: Java heap space

        at java.nio.HeapByteBuffer.<init>(Unknown Source)

        at java.nio.ByteBuffer.allocate(Unknown Source)

        at shadow.bundletool.com.android.apksig.internal.util.VerityTreeBuilder.digestDataByChunks(VerityTreeBuilder.java:245)

        at shadow.bundletool.com.android.apksig.internal.util.VerityTreeBuilder.generateVerityTree(VerityTreeBuilder.java:158)

        at shadow.bundletool.com.android.apksig.internal.util.VerityTreeBuilder.generateVerityTreeRootHash(VerityTreeBuilder.java:125)

        at shadow.bundletool.com.android.apksig.internal.util.VerityTreeBuilder.generateVerityTreeRootHash(VerityTreeBuilder.java:117)

        at shadow.bundletool.com.android.apksig.internal.apk.ApkSigningBlockUtils.computeApkVerityDigest(ApkSigningBlockUtils.java:777)

        at shadow.bundletool.com.android.apksig.internal.apk.ApkSigningBlockUtils.computeContentDigests(ApkSigningBlockUtils.java:454)

        at shadow.bundletool.com.android.apksig.internal.apk.ApkSigningBlockUtils.computeContentDigests(ApkSigningBlockUtils.java:1146)

        at shadow.bundletool.com.android.apksig.internal.apk.v2.V2SchemeSigner.generateApkSignatureSchemeV2Block(V2SchemeSigner.java:151)

        at shadow.bundletool.com.android.apksig.DefaultApkSignerEngine.outputZipSectionsInternal(DefaultApkSignerEngine.java:851)

        at shadow.bundletool.com.android.apksig.DefaultApkSignerEngine.outputZipSections2(DefaultApkSignerEngine.java:817)

        at shadow.bundletool.com.android.apksig.ApkSigner.sign(ApkSigner.java:555)

        at shadow.bundletool.com.android.apksig.ApkSigner.sign(ApkSigner.java:204)

        at com.android.tools.build.bundletool.io.ApkSigner.signApk(ApkSigner.java:99)

        at com.android.tools.build.bundletool.io.ModuleSplitSerializer.serializeAndSignSplit(ModuleSplitSerializer.java:256)

        at com.android.tools.build.bundletool.io.ModuleSplitSerializer.lambda$null$0(ModuleSplitSerializer.java:160)

        at com.android.tools.build.bundletool.io.ModuleSplitSerializer$$Lambda$641/12578653.call(Unknown Source)

        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)

        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)

        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

        at java.lang.Thread.run(Unknown Source)

java.lang.OutOfMemoryError: Java heap space

[com.android.tools.build.bundletool.io.ConcurrencyUtils.waitFor(ConcurrencyUtils.java:58), com.android.tools.build.bundletool.io.ConcurrencyUtils.waitForAll(ConcurrencyUtils.java:36), com.android.tools.build.bundletool.io.ModuleSplitSerializer.serialize(ModuleSplitSerializer.java:168), com.android.tools.build.bundletool.io.ApkSerializerManager.serializeApks(ApkSerializerManager.java:257), com.android.tools.build.bundletool.io.ApkSerializerManager.serializeApkSetContent(ApkSerializerManager.java:164), com.android.tools.build.bundletool.io.ApkSerializerManager.serializeApkSet(ApkSerializerManager.java:131), com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:222), com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:835), ir.cafebazaar.bundlesigner.BundleToolWrapper.buildApkSet(BundleToolWrapper.java:70), ir.cafebazaar.bundlesigner.command.GenBinCommand.execute(GenBinCommand.java:119), ir.cafebazaar.bundlesigner.BundleSignerTool.getContentDigest(BundleSignerTool.java:372), ir.cafebazaar.bundlesigner.BundleSignerTool.main(BundleSignerTool.java:126)]
```
![cmd](https://user-images.githubusercontent.com/24684851/202286090-f6a26e29-f3d4-453c-bf04-6e29e926e658.png)

**Comment by Siavash149** [comment]
من فقط این خطا رو داشتم: Java heap space (این بخش رو نداشتم java.lang.OutOfMemoryError:)
و با jre1.8.0_351 مشکل رفع شد.
