### ISSUE TITLE
مشکلم خطای زیر هست

### ISSUE THREAD

**Issue by mohammadMahdiAghajani** [cafebazaar/bundle-signer#41]
Keystore password for signer #1:
اینجا ورودی میخواد نمیدونم چی بدم.
بعد خطای زیر رو میده.
Failed to load signer "signer #1"
java.io.FileNotFoundException: key.jks (The system cannot find the file specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at ir.cafebazaar.bundlesigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:363)
        at ir.cafebazaar.bundlesigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:250)
        at ir.cafebazaar.bundlesigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:183)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.getSignerConfig(BundleSignerTool.java:448)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.getContentDigest(BundleSignerTool.java:357)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.main(BundleSignerTool.java:126)

**Comment by maze1377** [comment]
باعرض سلام,
به نظر میرسد مسیر فایل KeyStore خود را که با فلگ زیر مشخص میکنید:
```
--ks
```
به اشتباه وارد شده است و باعث میشود که موقع خوندن فایل در خط زیر:
https://github.com/cafebazaar/bundle-signer/blob/main/src/main/java/ir/cafebazaar/bundlesigner/SignerParams.java#L363
نتواند فایل را پیدا کند.

در مورد ورودی که از شما خواسته شده رمز فایل KeyStore شما میباشد.
میتواینید لینک زیر را برای مطالعه بیشتر بخوانید:
https://developers.cafebazaar.ir/fa/guidelines/build-app/app-signature#
