### ISSUE TITLE
خطای زیر هنگام ساخت فایل bin

### ISSUE THREAD

**Issue by feryt20** [cafebazaar/bundle-signer#47]
Failed to load signer "signer #1"
java.io.IOException: parseAlgParameters failed: ObjectIdentifier() -- data isn't an object ID (tag = 48)
        at java.base/sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(Unknown Source)
        at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(Unknown Source)
        at java.base/sun.security.util.KeyStoreDelegator.engineLoad(Unknown Source)
        at java.base/java.security.KeyStore.load(Unknown Source)
        at ir.cafebazaar.bundlesigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:364)
        at ir.cafebazaar.bundlesigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:250)
        at ir.cafebazaar.bundlesigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:183)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.getSignerConfig(BundleSignerTool.java:448)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.getContentDigest(BundleSignerTool.java:357)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.main(BundleSignerTool.java:126)
Caused by: java.io.IOException: ObjectIdentifier() -- data isn't an object ID (tag = 48)
        at java.base/sun.security.util.ObjectIdentifier.<init>(Unknown Source)
        at java.base/sun.security.util.DerInputStream.getOID(Unknown Source)
        at java.base/com.sun.crypto.provider.PBES2Parameters.engineInit(Unknown Source)
        at java.base/java.security.AlgorithmParameters.init(Unknown Source)
        ... 10 more

**Comment by ehsanwwe** [comment]
واقعا انتظار جواب داشتی ؟

**Comment by maze1377** [comment]
سلام، ممنون بابت گزارش مشکل.
برای حل مشکلم اطلاعات بیشتری نیاز دارم:
- نسخه دقیق Java و سیستم‌عامل را ذکر کنید
- با کلید تستی که داخل پوشه زیر وجود داره هم امضا کردن برنامه را تست کنید و ببیند آیا مشکل دوباره تکرار میشود یا خیر؟  https://github.com/cafebazaar/bundle-signer/tree/main/.github/workflows/test_resources
- کامندی که برای اجرا هم استفاده میکنید را بنویسید.
اگر این اطلاعات را ارائه دهید، می‌توانم بهتر مشکل شما را بررسی کنم و راه حلی پیشنهاد دهم. منتظر پاسخ شما هستم.

**Comment by maze1377** [comment]
با توجه به عدم دریافت پاسخی از سوی شما، فرض می‌کنیم که مشکل شما حل شده است. در صورتی که مشکل هنوز برای شما ادامه دارد، لطفاً یک مشکل جدید ایجاد کنید تا بتوانیم به آن پاسخ دهیم.
با تشکر
