### ISSUE TITLE
خطای باندل ساینر

### ISSUE THREAD

**Issue by PurTahan** [cafebazaar/bundle-signer#5]
سلام
همون طور که در #3  اطلاع دادم، جهت تهیه خروجی مد نظر بازار، از ابزار تعبیه شده استفاده کردم اما با خطای زیر روبرو شدم.
```
java.io.FileNotFoundException: C:\Users\PurTahan\AppData\Local\Temp\bundle_signer12986508944876332183\splits\base-arm64_v8a_?.apk (The filename, directory name, or volume label syntax is incorrect)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:343)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:258)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:213)
        at ir.cafebazaar.apksig.ApkSigner.addSignV1ToApk(ApkSigner.java:591)
        at ir.cafebazaar.apksig.ApkSigner.addSignV1ToApk(ApkSigner.java:564)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.calculateSignOfApk(BundleSignerTool.java:489)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.signApkSet(BundleSignerTool.java:440)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.getContentDigest(BundleSignerTool.java:347)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.main(BundleSignerTool.java:107)
Warning: Failed to remove tmp dir.
```

![image](https://user-images.githubusercontent.com/4592452/126863724-5d15fd9f-5aa8-47dc-a555-7750fb71dab2.png)

بعد از بررسی پوشه تمپ ایجاد شده متوجه شدم باندل ساینر نتونسته فایل `.apks` رو تبیدل به فایل های `.apk` کنه
بعد از چند بار تست متوجه شدم اگه اسم فایل `app.aab` باشه این مرحله انجام میشه اما دوباره خطا میده

![image](https://user-images.githubusercontent.com/4592452/126863740-454d2719-a565-47b4-89bf-b29d496020ac.png)

![image](https://user-images.githubusercontent.com/4592452/126863774-1f94829c-34f3-42f5-b4b7-e51dcb840d20.png)

تست های دیگه‌ای هم انجام دادم مثل تغییر پوشه جاری
تغییر اسم و پسوند فایل کلید
اما دیگه موفق نشدم جلوتر برم.

با توجه به اینکه برای انتشار برنامه‌ام در بازار نیاز به عبور از این مرحله هستم، ممنون میشم هرچه زودتر این مشکل رو برطرف کنید و یا با راهنمایی‌تون بهم کمک کنید.
با تشکر

**Comment by PurTahan** [comment]
همون طور که تو متن خطا نوشته در قسمت انتهای نام فایل علامت سوال قرار گرفته و تو تصویر سوم عدد 2 فارسی در اسم فایل وجود داره.
مطمئن نیستم، اما احتمال داره به خاطر این کاراکتر فارسی که باندل ساینر خودش تولید کرده نمیتونه فایل رو بخونه.

امیدوارم با این گزارشم تونسته باشم به تیم خوبتون کمک کرده باشم

**Comment by mahboobehad** [comment]
سلام 
ممنون از وقتی که گذاشتید. لطفا پکیج نیم برنامه‌تون که در بازار قرار داره رو بفرمایید تا بتونیم  بررسی کنیم.

**Comment by PurTahan** [comment]
com.qeraatmob

**Comment by mahboobehad** [comment]
داریم بررسی می‌کنیم اگه ممکنه تا زمانی که مشکل حل بشه از سیستم‌عامل دیگه‌ای مثل لینوکس استفاده کنید.

**Comment by PurTahan** [comment]
ممنونم، از طریق wsl موفق شدم خروجی بگیریم.

**Comment by alirezarastegarfard** [comment]
change regional format of windows  to English
