### ISSUE TITLE
Can not signer to aab，Because the size exceeds the limit.  aab Size 1G

### ISSUE THREAD

**Issue by wumiao1990** [cafebazaar/bundle-signer#50]
java -Xms2048m -Xmx6096m -jar bundlesigner-0.1.13.jar genbin  -v --bundle app.aab --bin . --v2-signing-enabled false --v3-signing-enabled true --ks wm.jks -v
Keystore password for signer #1:

java.io.IOException: Required capacity too large: 2147963846, max: 2147482623
        at ir.cafebazaar.apksig.internal.util.ByteArrayDataSink.ensureAvailable(ByteArrayDataSink.java:107)
        at ir.cafebazaar.apksig.internal.util.ByteArrayDataSink.consume(ByteArrayDataSink.java:85)
        at ir.cafebazaar.apksig.internal.util.FileChannelDataSource.feed(FileChannelDataSource.java:122)
        at ir.cafebazaar.apksig.internal.zip.LocalFileRecord.outputRecord(LocalFileRecord.java:304)
        at ir.cafebazaar.apksig.ApkSigner.outputInputJarEntryLfhRecordPreservingDataAlignment(ApkSigner.java:1963)
        at ir.cafebazaar.apksig.ApkSigner.genV1Bin(ApkSigner.java:408)
        at ir.cafebazaar.apksig.ApkSigner.genV1Bin(ApkSigner.java:220)
        at ir.cafebazaar.bundlesigner.command.GenBinCommand.calculateSignOfApk(GenBinCommand.java:175)
        at ir.cafebazaar.bundlesigner.command.GenBinCommand.extractAndSignApkSet(GenBinCommand.java:155)
        at ir.cafebazaar.bundlesigner.command.GenBinCommand.execute(GenBinCommand.java:127)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.getContentDigest(BundleSignerTool.java:377)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.main(BundleSignerTool.java:126)
content == null
[ir.cafebazaar.apksig.ApkSigner$Builder.setSignDigest(ApkSigner.java:2534), ir.cafebazaar.bundlesigner.command.GenBinCommand.calculateSignOfApk(GenBinCommand.java:178), ir.cafebazaar.bundlesigner.command.GenBinCommand.extractAndSignApkSet(GenBinCommand.java:155), ir.cafebazaar.bundlesigner.command.GenBinCommand.execute(GenBinCommand.java:127), ir.cafebazaar.bundlesigner.BundleSignerTool.getContentDigest(BundleSignerTool.java:377), ir.cafebazaar.bundlesigner.BundleSignerTool.main(BundleSignerTool.java:126)]

**Comment by mahboobehad** [comment]
If the issue stays please contact the developer support team or reopen the issue, providing the size of the bundle file and available memory to allocate.
